name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set environment variables
        run: env
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy with Docker Compose & executing tests
        run: |
          docker-compose down
          docker-compose up -d
          docker compose exec api python manage.py test
