name: Secrets and environment Variables

on:
    workflow_dispatch


jobs:
    set_secrets:
        runs-on: ubuntu-latest
        steps:
        - name: Set secrets
            run: |
                echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
                echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> $GITHUB_ENV
                echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> $GITHUB_ENV
                echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
                echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
                echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
                echo "POSTGRES_HOST_AUTH_METHOD=${{ secrets.POSTGRES_HOST_AUTH_METHOD }}" >> $GITHUB_ENV
                echo "POSTGRES_INITDB_ARGS=${{ secrets.POSTGRES_INITDB_ARGS }}" >> $GITHUB_ENV
                echo "CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}" >> $GITHUB_ENV
                echo "CELERY_ENABLE_UTC=${{ secrets.CELERY_ENABLE_UTC }}" >> $GITHUB_ENV
                echo "CELERY_DEFAULT_RETRY_DELAY=${{ secrets.CELERY_DEFAULT_RETRY_DELAY }}" >> $GITHUB_ENV
                echo "CELERY_DEFAULT_ASYNC_DELAY=${{ secrets.CELERY_DEFAULT_ASYNC_DELAY }}" >> $GITHUB_ENV
                echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> $GITHUB_ENV
                echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> $GITHUB_ENV
                echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV
        env:
            SECRET_KEY: ${{ vars.SECRET_KEY }}
            POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
            POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
            POSTGRES_DB: ${{ vars.POSTGRES_DB }}
            POSTGRES_USER: ${{ vars.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
            POSTGRES_HOST_AUTH_METHOD: ${{ vars.POSTGRES_HOST_AUTH_METHOD }}
            POSTGRES_INITDB_ARGS: ${{ vars.POSTGRES_INITDB_ARGS }}
            CELERY_BROKER_URL: ${{ vars.CELERY_BROKER_URL }}
            CELERY_ENABLE_UTC: ${{ vars. CELERY_ENABLE_UTC}}
            CELERY_DEFAULT_RETRY_DELAY: ${{ vars.CELERY_DEFAULT_RETRY_DELAY }}
            CELERY_DEFAULT_ASYNC_DELAY: ${{ vars.CELERY_DEFAULT_ASYNC_DELAY }}
            REDIS_HOST: ${{ vars.REDIS_HOST }}
            REDIS_PORT: ${{ vars.REDIS_PORT }}
            REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}